import axios from "axios";
import {React, useEffect, useState} from 'react'
import { useRouter } from "next/router"
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Head from "next/head";
import MultiActionAreaCard from "../components/movieCard";

function More(props) {

    const router = useRouter();
    const movieid = router.query.pageno;

    var [movie, setMovie] = useState({});
    var [backdrop, setBack] = useState("");
    var [genres, setGenres] = useState({});

    async function newMovie() {
        try {
          const searchRes = await axios.get(
            `https://api.themoviedb.org/3/movie/${movieid}?api_key=34a470327cec0df094785c27a8b66230`
            
          );
          setMovie(searchRes.data);
          setBack(searchRes.data.backdrop_path);
          setGenres(searchRes.data.genres);
          console.log("genres here" + genres);
        } catch (error) {
          console.log(error.searchRes);
        }
      }
      useEffect(()=>{
        newMovie();
      }, []);
      console.log(movie);

  return (
    <div style={{height: "100vh", width: "100vw", display: 'flex', justifyContent: 'center', backgroundColor: 'pink', alignItems: 'center', backgroundImage: `linear-gradient( rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)), url(${`https://image.tmdb.org/t/p/original/${backdrop}`})`}}>
        <Head>
        <title>{movie.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="pics" style={{display: 'flex' ,height: "90vh", width: "90vw", backgroundColor: "black", backgroundColor: "rgba(229,229,229, 0.2)", borderRadius: "15px", padding: "10px"}}>
  
            <img alt="poster" src={`https://image.tmdb.org/t/p/original${movie.poster_path}`} style={{height: "99%", width: "30%", borderRadius: '12px', alignItems: 'center'}}></img>

            <div style={{height: "99%", width: '60%', paddingLeft: '10%',  borderRadius: '12px', display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
              <h1 style={{color: 'white', marginBottom: '150px'}}> {movie.title}</h1>
              <div style={{display: 'flex', flexDirection: 'column', justifyContent: 'flex-start'}}>
              <p style={{color: 'white', alignSelf: 'flex-start'}}> popularity: {movie.popularity}</p>
              <p style={{color: 'white'}}> release date: {movie.release_date}</p>
              <p style={{color: 'white'}}> IMDB rating: {movie.vote_average}</p>
              <p style={{color: 'white'}}> duration : {movie.runtime}mins</p>
              <p style={{color: 'white'}}>{movie.overview}</p>
              </div>
              
                
            </div>
        </div>
    </div>
  )
}

export default More