import { Box } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import MultiActionAreaCard from '../components/movieCard'
import ResponsiveAppBar from '../components/navbar'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import { useEffect, useState } from 'react'

export default function Home() {

  const pic = "/twilight.jpeg"
  const title = "Twilight"
  var about = "This is a movie"
  var [movies, setMovies] = useState([]);

  async function getHandle() {
    try {
      const response = await axios.get(`https://api.themoviedb.org/3/tv/popular?api_key=34a470327cec0df094785c27a8b66230&language=en-US&page=1`);
      
      setMovies(response.data.results);
      // console.log(movies);
    } catch (error) {
      console.log(error.response.status);
    }
  }

  useEffect(() => {
    getHandle();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      {/* {console.log(movies)} */}
      <Box sx={{ display: "flex", flexWrap: 'wrap', justifyContent: 'space-evenly' }}>
        {
          movies.map((items, index)=>{
            console.log(items);
            return(
              <MultiActionAreaCard key = {index} title = {items.title} about = {items.overview} pic = {items.poster_path}/>
            );
          })
        }
      </Box>


    </div>
  )
}
