import {React, useState, useEffect} from 'react'
import { Box, Button } from '@mui/material'
import Navbar from '../components/navbar'
import axios from 'axios';
import MultiActionAreaCard from '../components/movieCard'
import Head from 'next/head'

function Trending(props) {

    var [movies, setMovies] = useState([]);
    var [ind, setInd] = useState(1);
    function handleNext(){
      console.log(next);
      setInd(ind+1);
    }
    function handlePrev(){
      setInd(ind>1?ind-1:ind);
    }

    async function getHandle() {
      try {
        const response = await axios.get(`https://api.themoviedb.org/3/trending/all/day?api_key=34a470327cec0df094785c27a8b66230&page=${ind}`);
        setMovies(response.data.results);
        console.log(response);
      } catch (error) {
        console.log(error.response.status);
      }
    }

    // async function getHandle() {
    //   try {
    //     const response = await axios.get(`https://api.themoviedb.org/3/search/movie?api_key=34a470327cec0df094785c27a8b66230&language=en-US&query=iron&page=1&include_adult=true`);
    //     setMovies(response.data.results);
    //     console.log(response);
    //   } catch (error) {
    //     console.log(error.response.status);
    //   }
    // }


  
    useEffect(() => {
      getHandle();
    }, [ind]);

  return (
    <>
        <Head>
        <title>Trending</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
        <Box sx={{ display: "flex", flexWrap: 'wrap', justifyContent: 'space-evenly' }}>
        {
          movies.map((items, index)=>{
            return(
              <MultiActionAreaCard key = {index} title = {items.title} about = {items.overview} pic = {items.poster_path} release = {items.release_date
              }
                rating = {items.vote_average}
              />
            );
          })
        }
      </Box>
      <Box
      sx={{
        display: 'flex',
        flexWrap: 'wrap',
        height: 150,
        width: "100%",
        backgroundImage: `url(./background.jpg)`,
        justifyContent: "center"
      }}
      >
        <Button onClick={handlePrev} variant="contained" sx={{m: 9}}>
          Back
        </Button>
        <Button onClick={handleNext} variant="contained" sx={{m: 9}}>
          Next
        </Button>
      </Box>
    </>
  )
}

export default Trending