import {React, useState, useEffect} from 'react'
import { Box } from '@mui/material'
import Navbar from '../components/navbar'
import axios from 'axios';
import MultiActionAreaCard from '../components/movieCard'
import Head from 'next/head'

function Trending(props) {
    const hod = "./hod.jpg"
    const title = "House of The Dragons"

    var [movies, setMovies] = useState([]);

    async function getHandle() {
      try {
        const response = await axios.get(`https://api.themoviedb.org/3/trending/all/day?api_key=34a470327cec0df094785c27a8b66230`);
        setMovies(response.data.results);
        console.log(response);
      } catch (error) {
        console.log(error.response.status);
      }
    }
  
    useEffect(() => {
      getHandle();
    }, []);

  return (
    <>
        <Head>
        <title>Trending</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
        <Box sx={{ display: "flex", flexWrap: 'wrap', justifyContent: 'space-evenly' }}>
        {
          movies.map((items, index)=>{
            return(
              <MultiActionAreaCard key = {index} title = {items.title} about = {items.overview} pic = {items.poster_path} release = {items.release_date
              }
                rating = {items.vote_average}
              />
            );
          })
        }
      </Box>
    </>
  )
}

export default Trending